account_mapping:
  - pattern: "^Account Name 1"
    extractor: A

description_mapping:
  "^TAX": "Taxes"
  "TAXES": "Taxes"
  "Property Tax": "Taxes"
  "grocery store": "Groceries"
  "market": "Groceries"

ingest:
  # db_type: csv
  db_type: google_sheets
  spreadsheet_name: Transactions
  worksheet_name: Documents_RAW

extract:
  # db_type: csv
  db_type: google_sheets
  spreadsheet_name: Transactions
  worksheet_name: Documents_RAW_EXTRACTED
